### ISSUE TITLE
Error spam and doesn't work with URP 13.1.8

### ISSUE THREAD

**Issue by ArtyIF** [voxell-tech/URPVolumetricLighting#1]
**Describe the bug**
When using this package with URP 13.1.8 (tested on Unity 2022.1.3f1) the console gets flooded with the following error message: `You can only call cameraColorTarget inside the scope of a ScriptableRenderPass. Otherwise the pipeline camera target texture might have not been created or might have already been disposed.` This also causes for light scattering to not work, only the top UI part of the scene view gets affected.

**To Reproduce**
1. Make sure that the project has Universal RP 13.1.8 installed
2. Add the Volumetric Light Scattering render feature
3. See error

**Expected behavior**
Package works fine, light gets scattering in proper places.

**Screenshots**
![image](https://user-images.githubusercontent.com/8017858/172998281-e46be7c4-186b-47b8-9a4c-53ad7ddbf05a.png)

**Desktop:**
 - OS: Fedora 36
 - Rendering API: Vulkan
 - GPU: Nvidia GeForce GTX 1050 Ti

**Additional context**
I remember URP's sample keep frame render feature having a similar issue.

**Comment by nixonyh** [comment]
hey, yeah I have heard similar reports on this issue before.. will need to check it out, if not mistaken, this error will only show when it's using unity 2022 version, it still works fine in 2021
