### ISSUE TITLE
Unity version is incorrect in package.json

### ISSUE THREAD

**Issue by andybak** [voxell-tech/URPVolumetricLighting#4]
It says 2020.3 but I'm guessing from the use of SetupRenderPasses that this needs 2022.1 at least.

Maybe this needs to go in the readme as well? - not everyone knows to look inside the json.

**Comment by nixonyh** [comment]
indeed, gotta change it ASAP

**Comment by nixonyh** [comment]
made the changes in this commit: https://github.com/voxell-tech/URPVolumetricLighting/commit/f85d80ad44d5cb7ac1dec8cbacaf5815fd659649
